In [3]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [5]:
z=[1,2,3]
z=np.array(z)
print(1/(1+np.exp(-z)))

[0.73105858 0.88079708 0.95257413]


In [6]:
x=[0,127,128,225]
x=np.array(x)
shape = (x.shape[0])
new_x = (x >= 128).astype(int)
new_x = np.reshape(new_x, shape)
print(new_x)

[0 0 1 1]
